edition = "2021"
hard_tabs = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
# nightly
condense_wildcard_suffixes = false
format_code_in_doc_comments = true
format_macro_bodies = true
hex_literal_case = 'Upper'
imports_granularity = 'One'
normalize_doc_attributes = true
wrap_comments = true
